import { type BaseRawTable } from '../../src/entities/raw-table/models'
import { systemUser } from './users'

export const countriesRawTable: BaseRawTable = {
  kn: 'countries',
  display: 'Страны',
  name: 'countries',
  nav: true,
  defaultView: 'table',
  description: 'Этот словарь был создан автоматически для примера',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  createdById: systemUser.id,
  updatedById: systemUser.id,
  columns: [
    {
      id: 'id1',
      name: 'code',
      display: 'Код',
      type: 'string',
      primary: true,
      maxLength: 2,
    },
    {
      id: 'id2',
      name: 'name',
      display: 'Название',
      type: 'string',
      unique: false,
      maxLength: 50,
    },
    {
      id: 'id3',
      name: 'dial_code',
      display: 'Телефоный код',
      type: 'string',
      unique: false,
      maxLength: 5,
    },
  ],
}

export const employeesRawTable: BaseRawTable = {
  kn: 'employees',
  display: 'Работники',
  name: 'employees',
  nav: true,
  defaultView: 'table',
  description: 'Этот словарь был создан автоматически для примера',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  createdById: systemUser.id,
  updatedById: systemUser.id,
  columns: [
    {
      id: 'id1',
      name: 'id',
      display: 'ID',
      type: 'integer',
      index: true,
      primary: true,
      maxLength: 50,
      isNegativeAllowed: false,
    },
    {
      id: 'id2',
      name: 'firstname',
      display: 'Имя',
      type: 'string',
      index: true,
      unique: false,
      maxLength: 50,
    },
    {
      id: 'id3',
      name: 'secondname',
      display: 'Фамилия',
      type: 'string',
      index: false,
      unique: false,
      maxLength: 50,
    },
    {
      id: 'id4',
      name: 'sex',
      display: 'Пол',
      type: 'string',
      unique: false,
      maxLength: 10,
    },
    {
      id: 'id5',
      name: 'age',
      display: 'Возраст',
      type: 'integer',
      unique: false,
      maxLength: 3,
      isNegativeAllowed: false,
    },
  ],
}

export const rfSubjectsRawTable: BaseRawTable = {
  kn: 'rfSubjects',
  display: 'Субъекты РФ',
  name: 'rf_subjects',
  nav: true,
  defaultView: 'table',
  description: 'Этот словарь был создан автоматически для примера',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  createdById: systemUser.id,
  updatedById: systemUser.id,
  columns: [
    {
      id: 'id1',
      name: 'capital',
      display: 'Столица',
      type: 'string',
      maxLength: 50,
    },
    {
      id: 'id2',
      name: 'name',
      display: 'Название',
      type: 'string',
      unique: false,
      maxLength: 50,
    },
    {
      id: 'id3',
      name: 'region_code',
      display: 'Код региона',
      type: 'string',
      primary: true,
      maxLength: 3,
    },
  ],
}
