version: '3.9'

x-default: &default-settings
  restart: always
  networks:
    - dnp-server-network

services:
  postgres:
    <<: *default-settings
    hostname: postgres
    image: ${POSTGRES_REPOSITORY:-}postgres:${POSTGRES_IMAGE_TAG:-15.6-bookworm}
    environment:
      POSTGRES_DB: '${POSTGRES_DB:-dnp_db}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-dnp_db_password}'
      POSTGRES_USER: '${POSTGRES_USER:-dnp_user}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    stop_grace_period: 60s
    ports:
      - '${POSTGRESQL_PORT:-5432}:5432'

  server-ui:
    <<: *default-settings
    build:
      context: .
      dockerfile: Dockerfile
    image:  dnp-server-ui:0.13
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-dnp_user}:${POSTGRES_PASSWORD:-dnp_db_password}@${POSTGRES_HOST:-postgres}/${POSTGRES_DB:-dnp_db}?schema=public"
      OPERATIONAL_DATABASE_URL: "postgresql://${POSTGRES_USER:-dnp_user}:${POSTGRES_PASSWORD:-dnp_db_password}@${POSTGRES_HOST:-postgres}/${POSTGRES_DB:-operational}?schema=public"
      TARGET_DATABASE_URL: "postgresql://${POSTGRES_USER:-dnp_user}:${POSTGRES_PASSWORD:-dnp_db_password}@${POSTGRES_HOST:-postgres}/${POSTGRES_DB:-target}?schema=public"
    ports:
      - "${UI_SERVER_PORT:-3000}:3000"
    depends_on:
      - postgres

networks:
  dnp-server-network:
    name: dnp-server-network

volumes:
  postgres-data:
    name: dnp-server-postgres-data
